# Configured by: booth config --no-tui --overwrite --cmd bash --select zig/claude-code



variant = "base"

run-args = [
    "-v", "~/.claude.json:/etc/cb-home-seed/.claude.json:ro",
    "-v", "~/.claude/.credentials.json:/etc/cb-home/.claude/.credentials.json:ro"
]
